#pragma once
enum EnemyState
{
	STATE_CHASE,
	STATE_ONDAMAGE,
	STATE_WALKBACK,
	STATE_DIE,
	STATE_GROUNDATTACK,
	STATE_RUNLEFT,
	STATE_CHARGE,
	STATE_RUNRIGHT,
	STATE_WINDATTACK,
	STATE_WATERATTACK,
	STATE_FIREATTACK,
	STATE_JUMPATTACK,
	STATE_IDLE,
};