#pragma once
//アニメーションを変更するときはanimation_dataの中身を変更することをわすれないで！！！
enum EnemyState : int
{
	STATE_WALKBACK,
	STATE_DIE,
	STATE_SPECIAL_CHARGE,
	STATE_FLOAT,
	STATE_SPECIALATTACK,
	STATE_RUNLEFT,
	STATE_CHARGE,
	STATE_RUNRIGHT,
	STATE_FIREATTACK,
	STATE_WATERATTACK,
	STATE_WINDATTACK,
	STATE_JUMPATTACK,
	STATE_IDLE,
	STATE_CHASE,
	STATE_ONDAMAGE,
};