#pragma once

enum PlayerState
{
	STATE_TAKE_ITEM,
	STATE_COMBAT_IDLE,
	STATE_COMBAT_IDLE_START,
	STATE_LEFT_PUNCH,
	STATE_RIGHT_PUNCH,
	STATE_BELOW,
	STATE_ATTACK_START,
	STATE_ATTACK,
	STATE_ATTACK_,
	STATE_HANDIDLE,
};